[nodes]
major-tom
ground-control

[nodes:vars]
ansible_user={{ lookup('env', 'ANSIBLE_USER') }}
ansible_ssh_private_key_file={{ lookup('env', 'ANSIBLE_PK') }}
ansible_python_interpreter=/usr/bin/python3

[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[slurm_hosts:children]
local
nodes