name: 'Cluster Status Check'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
  pull_request:
    branches: [ main ]
jobs:
  greet:
    runs-on: self-hosted
    steps:
      - name: Cluster Status Check
        shell: bash
        run: |
          echo "Hello from the $(hostname)!"
          failed=0
          for target in major-tom ground-control; do
            ping -c 5 "$target" || failed=1
          done
          exit $failed
      - name: Check Slurm Node Status
        shell: bash
        run: |
          sinfo -N -l
      - name: Run slurm jobs
        shell: bash
        run: |
          srun --chdir=/mnt/cluster-workspace/healthcheck -N1 -w ground-control /bin/bash -c 'echo "Hello from $(hostname)"'
          srun --chdir=/mnt/cluster-workspace/healthcheck -N1 -w major-tom /bin/bash -c 'echo "Hello from $(hostname)"'
          
