name: 'Main Workflow'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  greet:
    runs-on: self-hosted
    steps:
      - name: Cluster Status Check
        shell: bash
        run: |
          echo 'Hello from the $(hostname)!'
          failed=0
          for target in major-tom ground-control; do
            ping -c 5 "$target" || failed=1
          done
          exit $failed
